spring:
  datasource:    hikari:
      connection-test-query: SELECT 1
      allow-pool-suspension: true
  jpa:    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:      use-new-id-generator-mappings: false
mybatis:  configuration:    map-underscore-to-camel-case: true
---
spring:  profiles: dev
  datasource:    hikari:      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/testboard?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: homeground12!@
  thymeleaf:
    cache: false
  web:    resources:      cache:        period: 0
---
spring:  profiles: production
  datasource:    hikari:      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/testboard?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: homeground12!@